/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiEventsRouteImport } from './routes/api.events'
import { Route as ToolsBpmDelayCalculatorRouteImport } from './routes/tools.bpm-delay-calculator'
import { Route as ToolsFretCalculatorRouteImport } from './routes/tools.fret-calculator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBpmDelayCalculatorRoute = ToolsBpmDelayCalculatorRouteImport.update({
  id: '/tools/bpm-delay-calculator',
  path: '/tools/bpm-delay-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFretCalculatorRoute = ToolsFretCalculatorRouteImport.update({
  id: '/tools/fret-calculator',
  path: '/tools/fret-calculator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/events': typeof ApiEventsRoute
  '/tools/bpm-delay-calculator': typeof ToolsBpmDelayCalculatorRoute
  '/tools/fret-calculator': typeof ToolsFretCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/events': typeof ApiEventsRoute
  '/tools/bpm-delay-calculator': typeof ToolsBpmDelayCalculatorRoute
  '/tools/fret-calculator': typeof ToolsFretCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/events': typeof ApiEventsRoute
  '/tools/bpm-delay-calculator': typeof ToolsBpmDelayCalculatorRoute
  '/tools/fret-calculator': typeof ToolsFretCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/methodology'
    | '/privacy'
    | '/terms'
    | '/api/events'
    | '/tools/bpm-delay-calculator'
    | '/tools/fret-calculator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/methodology'
    | '/privacy'
    | '/terms'
    | '/api/events'
    | '/tools/bpm-delay-calculator'
    | '/tools/fret-calculator'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/methodology'
    | '/privacy'
    | '/terms'
    | '/api/events'
    | '/tools/bpm-delay-calculator'
    | '/tools/fret-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ToolsBpmDelayCalculatorRoute: typeof ToolsBpmDelayCalculatorRoute
  ToolsFretCalculatorRoute: typeof ToolsFretCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/bpm-delay-calculator': {
      id: '/tools/bpm-delay-calculator'
      path: '/tools/bpm-delay-calculator'
      fullPath: '/tools/bpm-delay-calculator'
      preLoaderRoute: typeof ToolsBpmDelayCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/fret-calculator': {
      id: '/tools/fret-calculator'
      path: '/tools/fret-calculator'
      fullPath: '/tools/fret-calculator'
      preLoaderRoute: typeof ToolsFretCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiEventsRoute: ApiEventsRoute,
  ToolsBpmDelayCalculatorRoute: ToolsBpmDelayCalculatorRoute,
  ToolsFretCalculatorRoute: ToolsFretCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
